# Generated by Django 3.1.5 on 2021-01-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('adress', models.CharField(max_length=225)),
                ('phonenumber', models.CharField(max_length=225)),
                ('discrict', models.CharField(max_length=225)),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pations.diagnos')),
            ],
        ),
    ]
